trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  resourceGroupName: 'Jaya0117'
  templateFile: 'main.bicep'
  location: 'centralus'

steps:
- task: AzureCLI@2
  displayName: 'Deploy Resources with Bicep'
  inputs:
    azureSubscription: 'defenderdemo2'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Deploying Azure resources using Bicep template..."
      az deployment group create \
        --resource-group $(resourceGroupName) \
        --template-file $(templateFile) \
        --parameters location=$(location)
      echo "Deployment completed."

- task: MicrosoftSecurityDevOps@1
  displayName: 'Scan for Vulnerabilities'
  inputs:
    scanType: 'Code'
    failOnCriticalIssues: true

- task: AzureCLI@2
  displayName: 'Check Vulnerabilities in Defender Dashboard'
  inputs:
    azureSubscription: 'defenderdemo2'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Checking security vulnerabilities in Microsoft Defender for Cloud..."
      az security assessment list --query "[?status.code=='Unhealthy']" --output table
      echo "Security scan completed. Review vulnerabilities in the Defender dashboard."
